webserver:
  host: 0.0.0.0
  port: 10140
  access-log:
    format: "%h %u %t %r %s %b %{Referer}i %T"


storage:
  provider: gcs
google:
  storage:
    provider:
      bucket: set-in-environment-variable
      topic: transactions-nets-2018
    secret:
      keyfile:
    credential:
      provider: compute-engine
    encryption: true
    buffer:
      lines: 10000
    local:
      temp:
        folder: "tmp/rawdata/nets/temp"

# Metrics related configurations
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics, scheduledtasks, mappings, loggers, logfile, beans
    enabled-by-default: true

tracing:
  enabled: true
  service: nets-app
  sampler-type: const
  sampler-param: 1
  propagation: b3
  protocol: http
  host: localhost
  port: 14268
  path: /api/traces
  paths:
    - path: "/favicon.ico"
      enabled: false
    - path: "/metrics"
      enabled: false
    - path: "/metrics/vendor"
      enabled: false
    - path: "/metrics/base"
      enabled: false
    - path: "/metrics/application"
      enabled: false
    - path: "/health"
      enabled: false
    - path: "/health/alive"
      enabled: false
    - path: "/health/ready"
      enabled: false

spring:
  # Don't print the Spring logo banner at startup (We want only JSON logs printed to stdout)
  main:
    banner-mode: off
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/forbruk-nets-app-db
    username: dummy_value
    password: dummy_value
  jpa:
    database: POSTGRESQL
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update


server:
  port: 8080

# Configuration used in connection to NETS
forbruk:
  nets:
    host: nets_ip_set_in_env_var
    user: netsusr_set_in_env_var
    port: 22
    session_timeout: 10000
    channel_timeout: 5000
    workdir: "./Outbound"
    privatekeyfile:
    filedir: "tmp/"
    header: "TRANSAKSJONSDATO;TRANSTYPESTATUS;KORTTJENESTE;BRUKERSTED_ORGNUMMER;BRUKERSTED_NAVN;KORTINNEH_KONTONR;VAREKJOP_BELOP;BELOEP_TOTALT"



# Scheduler (one hour earlier than local time in winter and two hours in summer-time)
scheduled:
  cron:
    handlefiles: "0 10 13 9 6 ?"
    cleantable: "0 25 6 18 5 ?"
    consume: "0 0/20 * 3 6 ?"
    listfilenames: "0 30 6 14 6 ?"
