webserver:
  host: 0.0.0.0
  port: 10140
  access-log:
    format: "%h %u %t %r %s %b %{Referer}i %T"


storage:
  provider: gcs
google:
  storage:
    provider:
      bucket: ssb-rawdata-prod-forbruk-nets
      topic: nets-2018-bankaxcept-transactions
    secret:
      keyfile:
    credential:
      provider: compute-engine
    encryption: true
    buffer:
      lines: 1000
    local:
      temp:
        folder: "tmp/rawdata/nets/temp"

# Metrics related configurations
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metric
#    base-path: /
#    path-mapping:
#      prometheus: health, metrics

tracing:
  enabled: true
  service: nets-app
  sampler-type: const
  sampler-param: 1
  propagation: b3
  protocol: http
  host: localhost
  port: 14268
  path: /api/traces
  paths:
    - path: "/favicon.ico"
      enabled: false
    - path: "/metrics"
      enabled: false
    - path: "/metrics/vendor"
      enabled: false
    - path: "/metrics/base"
      enabled: false
    - path: "/metrics/application"
      enabled: false
    - path: "/health"
      enabled: false
    - path: "/health/alive"
      enabled: false
    - path: "/health/ready"
      enabled: false

spring:
  # Don't print the Spring logo banner at startup (We want only JSON logs printed to stdout)
  main:
    banner-mode: off
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/forbruk-nets-app-db
    username: dummy_value
    password: dummy_value
  jpa:
    database: POSTGRESQL
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update


server:
  port: 8080

# Configuration used in connection to NETS
forbruk:
  nets:
    host: 91.102.24.144
    user: tSSBNO
    port: 22
    session_timeout: 10000
    channel_timeout: 5000
    workdir: "./Outbound"
    privatekeyfile:
    filedir: "tmp/"
    header: "TRANSAKSJONSDATO;TRANSAKSJONSTID;BRUKERSTED;KORTINNEH_KONTONR;VAREKJOP_BELOP;BELOEP_TOTALT;BR_STED_NAVN_TERM;BRUKERSTED_ORGNUMMER;BRUKERSTED_NAVN"



# Scheduler
scheduled:
  cron:
    listfiles: "0 0 5/4 * * ?"

