CREATE SEQUENCE IF NOT EXISTS SEQ_NEST_RECORD_ID;

CREATE TABLE IF NOT EXISTS NETS_RECORD
(
    ID               INTEGER DEFAULT nextval('SEQ_NETS_REC_ID') PRIMARY KEY,
    CONTENTS         VARCHAR(4000),
    TIMESTAMP        TIMESTAMP
);

